### ISSUE TITLE
build error with unexpected syntax in form ()

### ISSUE THREAD

**Issue by aconchillo** [artyom-poptsov/guile-ini#1]
Hi @artyom-poptsov. I'm trying to add `guile-ini` to homebrew guile but ran into this issue:

```
Making all in ini
cat fsm.puml | smc -L ../../modules -U "((ini fsm-context) (smc guards char) (smc core context))" --fsm-name ini-fsm --fsm-module "(ini fsm)" --validate > fsm.scm
  GUILEC   fsm.go
ice-9/boot-9.scm:1685:16: In procedure raise-exception:
Syntax error:
unknown location: unexpected syntax in form ()
make[2]: *** [fsm.go] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

I ran that line manually and I got:

```
❯ cat fsm.puml | smc -L ../../modules -U "((ini fsm-context) (smc guards char) (smc core context))" --fsm-name ini-fsm --fsm-module "(ini fsm)" --validate
()
```

I haven't investigated yet but just wanted it to report in case it sounded familiar to you.

Guile: 3.0.6
OS: macOS 11.2.3

**Comment by artyom-poptsov** [comment]
Hello,

what versions of Guile-INI and Guile-SMC did you test?

**Comment by aconchillo** [comment]
guile-ini from master and guile-smc 0.1.0.

**Comment by aconchillo** [comment]
Closing.

I was testing guile-smc 0.1.0 (installed from homebrew) and guile-ini master. I have now tested guile-smc 0.1.0 installed from homebrew and guile-ini 0.1.0 also installed from homebrew and it works fine.
